In [28]:
# Importing libraries and packages:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn import metrics
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import GridSearchCV

In [29]:
data = pd.read_csv('C:/Users/vivek/OneDrive/Desktop/college/5661/Project/manipulated/1000rows.csv')

In [30]:
data

,order_id,product_id,add_to_cart_order,reordered,order_id.1,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,0,0,0,0,0,0,eval_set,0,0,0,0
1,38,11913,1,0,38,42756,train,6,6,16,24
2,38,18159,2,0,38,42756,train,6,6,16,24
3,38,4461,3,0,38,42756,train,6,6,16,24
4,38,21616,4,1,38,42756,train,6,6,16,24
5,38,23622,5,0,38,42756,train,6,6,16,24
6,38,32433,6,0,38,42756,train,6,6,16,24
7,38,28842,7,0,38,42756,train,6,6,16,24
8,38,42625,8,0,38,42756,train,6,6,16,24
9,38,39693,9,0,38,42756,train,6,6,16,24
10,96,20574,1,1,96,17227,train,7,6,20,30
11,96,30391,2,0,96,17227,train,7,6,20,30
12,96,40706,3,1,96,17227,train,7,6,20,30
13,96,25610,4,0,96,17227,train,7,6,20,30
14,96,27966,5,1,96,17227,train,7,6,20,30
15,96,24489,6,1,96,17227,train,7,6,20,30
16,96,39275,7,1,96,17227,train,7,6,20,30
17,98,8859,1,1,98,56463,train,41,3,8,14
18,98,19731,2,1,98,56463,train,41,3,8,14
19,98,43654,3,1,98,56463,train,41,3,8,14
20,98,13176,4,1,98,56463,train,41,3,8,14
21,98,4357,5,1,98,56463,train,41,3,8,14
22,98,37664,6,1,98,56463,train,41,3,8,14
23,98,34065,7,1,98,56463,train,41,3,8,14
24,98,35951,8,1,98,56463,train,41,3,8,14
25,98,43560,9,1,98,56463,train,41,3,8,14
26,98,9896,10,1,98,56463,train,41,3,8,14
27,98,27509,11,1,98,56463,train,41,3,8,14
28,98,15455,12,1,98,56463,train,41,3,8,14
29,98,27966,13,1,98,56463,train,41,3,8,14
...,...,...,...,...,...,...,...,...,...,...,...
9969,80489,33043,21,1,80489,47175,train,9,0,16,30
9970,80489,36695,22,1,80489,47175,train,9,0,16,30
9971,80489,32864,23,1,80489,47175,train,9,0,16,30
9972,80489,34969,24,1,80489,47175,train,9,0,16,30
9973,80489,10246,25,0,80489,47175,train,9,0,16,30
9974,80489,30776,26,0,80489,47175,train,9,0,16,30
9975,80489,41621,27,0,80489,47175,train,9,0,16,30
9976,80489,22290,28,0,80489,47175,train,9,0,16,30
9977,80489,44625,29,0,80489,47175,train,9,0,16,30
9978,80489,41165,30,0,80489,47175,train,9,0,16,30
9979,80492,10749,1,0,80492,41805,train,4,2,14,30
9980,80492,13176,2,0,80492,41805,train,4,2,14,30
9981,80492,18867,3,1,80492,41805,train,4,2,14,30
9982,80492,45013,4,0,80492,41805,train,4,2,14,30
9983,80492,45763,5,0,80492,41805,train,4,2,14,30
9984,80492,30791,6,1,80492,41805,train,4,2,14,30
9985,80492,47209,7,1,80492,41805,train,4,2,14,30
9986,80492,47672,8,1,80492,41805,train,4,2,14,30
9987,80492,21614,9,1,80492,41805,train,4,2,14,30
9988,80492,12614,10,1,80492,41805,train,4,2,14,30
9989,80492,27104,11,1,80492,41805,train,4,2,14,30
9990,80707,13535,1,1,80707,15592,train,15,6,13,26
9991,80707,17902,2,1,80707,15592,train,15,6,13,26
9992,80721,13176,1,1,80721,50854,train,5,4,19,16
9993,80721,22035,2,1,80721,50854,train,5,4,19,16
9994,80721,39180,3,1,80721,50854,train,5,4,19,16
9995,80721,45,4,1,80721,50854,train,5,4,19,16
9996,80721,46584,5,1,80721,50854,train,5,4,19,16
9997,80721,17608,6,0,80721,50854,train,5,4,19,16
9998,80721,31504,7,0,80721,50854,train,5,4,19,16

In [31]:
feature_columns = ['order_id' ,'product_id' ,'add_to_cart_order' ,'user_id','order_number' ,'order_dow',
         'order_hour_of_day','days_since_prior_order' ]
X = data[feature_columns]
y = data['reordered']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [33]:
my_ANN = MLPClassifier(hidden_layer_sizes=(3,), activation= 'logistic', 
                       solver='adam', alpha=1e-5, random_state=1, 
                       learning_rate_init = 0.1)

In [34]:
my_ANN.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(3,), learning_rate='constant',
       learning_rate_init=0.1, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [35]:
y_predict_ann = my_ANN.predict(X_test)
#print(y_predict_ann)
score_ann = accuracy_score(y_test, y_predict_ann)
print(score_ann)

0.6225

In [36]:
# define a range for the "number of neurons" in the hidden layer for a network with 1 hidden layer:
neuron_number = [(i,j) for i in range(1,9) for j in range(1,9)]                    

# create a dictionary for grid parameter:
param_grid = dict(hidden_layer_sizes = neuron_number)
print(param_grid,'\n')

# instantiate the model:
my_ANN = MLPClassifier(activation='logistic', solver='adam', 
                                         alpha=1e-5, random_state=1, learning_rate_init = 0.1)

# creat the grid, and define the metric for evaluating the model: 
grid = GridSearchCV(my_ANN, param_grid, cv=10, scoring='accuracy')

# fit the grid (start the grid search):
grid.fit(X, y)

# view the results:
# print(grid.cv_results_)

# view the best results corresponding to the best structure of ANN:
print(grid.best_score_)
print(grid.best_params_)

{'hidden_layer_sizes': [(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8)]}

0.6164616461646165
{'hidden_layer_sizes': (1, 1)}